<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Logging -->
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- Project References -->
    <PackageReference Include="Markdig" Version="1.1.0" />
    <ProjectReference Include="..\Squirrel.Wiki.Contracts\Squirrel.Wiki.Contracts.csproj" />
  </ItemGroup>

</Project>
