using AutoMapper;
using Squirrel.Wiki.Core.Database.Entities;
using Squirrel.Wiki.Core.Models;

namespace Squirrel.Wiki.Core.Mapping;

/// <summary>
/// AutoMapper profile for Category entity mappings
/// Note: CategoryDto mapping requires additional data from repository (PageCount, ParentName, etc.)
/// and should be done via a custom mapping method in CategoryService
/// </summary>
public class CategoryMappingProfile : Profile
{
    public CategoryMappingProfile()
    {
        // Category -> CategoryDto (basic mapping only - service will enrich with repository data)
        CreateMap<Category, CategoryDto>()
            .ForMember(dest => dest.ParentId, opt => opt.MapFrom(src => src.ParentCategoryId))
            .ForMember(dest => dest.ParentCategoryId, opt => opt.MapFrom(src => src.ParentCategoryId))
            .ForMember(dest => dest.ParentName, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.PageCount, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.Level, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.Depth, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.FullPath, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.Path, opt => opt.Ignore()); // Set by service

        // CategoryCreateDto -> Category
        CreateMap<CategoryCreateDto, Category>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.Slug, opt => opt.Ignore()) // Generated by service
            .ForMember(dest => dest.ParentCategoryId, opt => opt.MapFrom(src => src.ParentId ?? src.ParentCategoryId))
            .ForMember(dest => dest.CreatedOn, opt => opt.MapFrom(_ => DateTime.UtcNow))
            .ForMember(dest => dest.ModifiedBy, opt => opt.MapFrom(src => src.CreatedBy))
            .ForMember(dest => dest.ModifiedOn, opt => opt.MapFrom(_ => DateTime.UtcNow))
            .ForMember(dest => dest.DisplayOrder, opt => opt.MapFrom(_ => 0))
            .ForMember(dest => dest.Pages, opt => opt.Ignore());

        // CategoryUpdateDto -> Category (for updating existing entity)
        CreateMap<CategoryUpdateDto, Category>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.Slug, opt => opt.Ignore()) // Generated by service
            .ForMember(dest => dest.ParentCategoryId, opt => opt.MapFrom(src => src.ParentId ?? src.ParentCategoryId))
            .ForMember(dest => dest.CreatedOn, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.ModifiedOn, opt => opt.MapFrom(_ => DateTime.UtcNow))
            .ForMember(dest => dest.DisplayOrder, opt => opt.Ignore())
            .ForMember(dest => dest.Pages, opt => opt.Ignore());

        // Category -> CategoryTreeDto (basic mapping - service will populate Children)
        CreateMap<Category, CategoryTreeDto>()
            .ForMember(dest => dest.PageCount, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.Children, opt => opt.Ignore()); // Set by service
    }
}
